[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
otc_swaps = "FDoRMA7k9uXybXW97bBU3979YG1ax4xf3Bf7jaAqYG48"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
